### ISSUE TITLE
Cant import cloudbot

### ISSUE THREAD

**Issue by pitastrudl** [nekosune/WeedBot#6]
script wants to import cloudbot but the module is nowhere to be found. any ideas?

**Comment by nekosune** [comment]
did you start from the BASE directory with
python3 -m cloudbot

**Comment by pitastrudl** [comment]
ubuntu@ip-172-31-8-106:~/skybot$ python3 -m cloudbot bot.py
/usr/bin/python3: No module named cloudbot

**Comment by nekosune** [comment]
do NOT include bot.py
JUST python3 -m cloudbot

**Comment by pitastrudl** [comment]
ubuntu@ip-172-31-8-106:~/skybot$ python3 -m cloudbot
/usr/bin/python3: No module named cloudbot
